export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS";
export const USER_LOGIN_LOADING="USER_LOGIN_LOADING";
export const USER_LOGIN_ERR="USER_LOGIN_Err";


export const USER_REGISTER_SUCCESS="USER_REGISTER_SUCCESS";
export const USER_REGISTER_LOADING="USER_REGISTER_LOADING";
export const USER_REGISTER_ERR="USER_REGISTER_ERR";

export const USER_LOG_OUT="UER_LOG_OUT";